name: Go
on:
  - push
  - pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev libspatialite-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: go test ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
