name: Go
on:
  - push
  - pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev libspatialite-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Make
      run: |
        make
